FROM ghcr.io/puppeteer/puppeteer:latest

USER root

# Instala dependências extras do sistema
RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

# Comando para rodar o bot
CMD ["node", "index.js"]